server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/F1NLEARN/config-server
          default-label: main
          clone-on-start: true
          force-pull: true

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_URL1:localhost}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      show-details: always